# Generated by Django 3.2.5 on 2022-01-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geschaeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('oeffnungszeiten', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Szene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('preis', models.FloatField(blank=True, null=True)),
                ('menge', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('szene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.szene')),
            ],
        ),
    ]
