# Generated by Django 3.2.5 on 2022-01-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charakter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('geschlecht', models.CharField(max_length=200)),
                ('beruf', models.TextField()),
                ('rasse', models.CharField(max_length=200)),
                ('alive', models.BooleanField(default=True)),
                ('kommentar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eintrag',
            name='szene',
        ),
        migrations.DeleteModel(
            name='Geschaeft',
        ),
        migrations.AddField(
            model_name='szene',
            name='kapitel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='szene',
            name='name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Eintrag',
        ),
        migrations.AddField(
            model_name='charakter',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ort'),
        ),
        migrations.AddField(
            model_name='charakter',
            name='szene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.szene'),
        ),
    ]
