# Generated by Django 3.2.5 on 2022-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reihenfolge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reihenfolge',
            name='name',
        ),
        migrations.AddField(
            model_name='reihenfolge',
            name='nummer',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reihenfolge',
            name='kapitelNr',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
