# Generated by Django 3.2.5 on 2022-02-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220201_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reihenfolge',
            name='nummer',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
