# Generated by Django 3.2.5 on 2022-02-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_reihenfolge_nummer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kapitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kapitelNr', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='szene',
            name='chronologie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='szene',
            name='kapitel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kapitel'),
        ),
        migrations.DeleteModel(
            name='Reihenfolge',
        ),
    ]
