# Generated by Django 3.2.5 on 2022-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220201_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('geschlecht', models.CharField(max_length=200)),
                ('beruf', models.TextField()),
                ('rasse', models.CharField(max_length=200)),
                ('alive', models.BooleanField(default=True)),
                ('kommentar', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Charakter',
        ),
    ]
