# Generated by Django 3.2.5 on 2022-02-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220201_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Szene',
        ),
    ]
