# Generated by Django 3.2.5 on 2022-02-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_szene'),
    ]

    operations = [
        migrations.AddField(
            model_name='szene',
            name='charakter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.figur'),
        ),
        migrations.AddField(
            model_name='szene',
            name='chronologie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='szene',
            name='kapitel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kapitel'),
        ),
        migrations.AddField(
            model_name='szene',
            name='ort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ort'),
        ),
        migrations.AlterField(
            model_name='figur',
            name='name',
            field=models.TextField(default='foobar'),
        ),
    ]
