# Generated by Django 3.2.5 on 2022-02-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220201_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szene',
            name='charakter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.figur'),
        ),
        migrations.AlterField(
            model_name='szene',
            name='kapitel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kapitel'),
        ),
        migrations.AlterField(
            model_name='szene',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ort'),
        ),
    ]
