# Generated by Django 3.2.5 on 2022-02-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220201_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='szene',
            name='beschreibung',
            field=models.TextField(null=True),
        ),
    ]
