# Generated by Django 3.2.5 on 2022-02-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_szene_beschreibung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szene',
            name='beschreibung',
            field=models.TextField(),
        ),
    ]
