# Generated by Django 3.2.5 on 2022-02-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_figurenliste'),
    ]

    operations = [
        migrations.AddField(
            model_name='figur',
            name='figurenliste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.figurenliste'),
        ),
    ]
