# Generated by Django 3.2.5 on 2022-02-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_figur_figurenliste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='szene',
            name='charakter',
        ),
    ]
