# Generated by Django 3.2.5 on 2022-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_szene_charakter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figur',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='szene',
            name='name',
            field=models.CharField(default='foobar', max_length=200),
        ),
    ]
