# Generated by Django 3.2.5 on 2022-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220203_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szene',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
