# Generated by Django 3.2.5 on 2022-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_szene_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figur',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='figur',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='szene',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
