# Generated by Django 3.2.5 on 2022-02-04 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220203_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figur',
            name='beruf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='figur',
            name='figurenliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.figurenliste'),
        ),
        migrations.AlterField(
            model_name='figur',
            name='geschlecht',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='figur',
            name='rasse',
            field=models.CharField(blank=True, default='Mensch', max_length=200, null=True),
        ),
    ]
