# Generated by Django 3.2.5 on 2022-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220204_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapitel',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
