# Generated by Django 3.2.5 on 2022-02-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_kapitel_kommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='szene',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
