# Generated by Django 3.2.5 on 2022-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_figurenliste_kommentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='kommentar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
