# Generated by Django 3.2.5 on 2022-02-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_ort_kommentar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figurenliste',
            name='kommentar',
        ),
    ]
