# Generated by Django 3.2.5 on 2022-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_figurenliste_kommentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='kapitel',
            name='kapitelNr',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='szene',
            name='chronologie',
            field=models.IntegerField(unique=True),
        ),
    ]
