# Generated by Django 3.2.5 on 2022-02-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
