# Generated by Django 3.2.5 on 2022-02-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
