# Generated by Django 3.2.5 on 2022-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_delete_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=80)),
                ('Price', models.IntegerField()),
                ('Genre', models.CharField(max_length=80)),
                ('Description', models.TextField()),
            ],
        ),
    ]
