# Generated by Django 5.1.1 on 2024-09-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='SampleBookModel',
        ),
    ]
