# Generated by Django 5.1.1 on 2024-09-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_delete_book_delete_samplebookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='geographische_lage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
