# Generated by Django 5.1.1 on 2024-09-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_ortliste'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='ortliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ortliste'),
        ),
    ]
