# Generated by Django 5.1.1 on 2024-09-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_ort_ortliste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ort',
            name='bedeutung_oder_funktion',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='beschreibung_des_ortes',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='bevölkerung_und_gesellschaft',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='flora_und_fauna',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='gefahren_und_bedrohungen',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='geographische_lage',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='gerüchte_und_legenden',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='historie_und_hintergrund',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='klima_und_wetter',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='kulturelle_oder_religiöse_bedeutung',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='magische_oder_mystische_eigenschaften',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='politische_verhältnisse',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='quests_und_interaktionsmöglichkeiten',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='ressourcen_und_reichtümer',
        ),
        migrations.RemoveField(
            model_name='ort',
            name='verbindungen_zu_anderen_orten',
        ),
        migrations.AddField(
            model_name='ortliste',
            name='bedeutung_oder_funktion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='beschreibung_des_ortes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='bevölkerung_und_gesellschaft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='flora_und_fauna',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='gefahren_und_bedrohungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='geographische_lage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='gerüchte_und_legenden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='historie_und_hintergrund',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='klima_und_wetter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='kulturelle_oder_religiöse_bedeutung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='magische_oder_mystische_eigenschaften',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='politische_verhältnisse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='quests_und_interaktionsmöglichkeiten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='ressourcen_und_reichtümer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='verbindungen_zu_anderen_orten',
            field=models.TextField(blank=True, null=True),
        ),
    ]
