# Generated by Django 5.1.1 on 2024-09-12 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_remove_ort_bedeutung_oder_funktion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schauplatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alive', models.BooleanField(default=True)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('ortliste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ort')),
            ],
        ),
    ]
