# Generated by Django 5.1.1 on 2024-09-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_szene_ort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szene',
            name='ort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ort'),
        ),
    ]
