# Generated by Django 5.1.1 on 2024-09-19 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_schauplatz_ebene2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schauplatz_ebene2',
            name='schauplatz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ort'),
        ),
    ]
