# Generated by Django 5.1.1 on 2024-09-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_schauplatz_ebene2_schauplatz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schauplatz_Ebene2',
        ),
    ]
