# Generated by Django 5.1.1 on 2024-09-19 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_delete_schauplatz_ebene2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alive', models.BooleanField(default=True)),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('schauplatz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.schauplatz')),
            ],
        ),
    ]
