# Generated by Django 5.1.1 on 2024-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='beleuchtung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='einrichtungsstil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='gefahren_und_bedrohungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='geheimnisse_und_versteckte_elemente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='nutzung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='quests_und_interaktionsmöglichkeiten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='raumtyp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='spezielle_gegenstände',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zustand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='architektur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='bedeutung_oder_funktion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='besitzer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='gefahren_und_bedrohungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='geheimnisse_und_legenden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='geschichte_des_schauplatzes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='quests_und_interaktionsmöglichkeiten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='typ',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='wichtige_personen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schauplatz',
            name='zustand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
