# Generated by Django 5.1.1 on 2024-09-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_location_beleuchtung_location_einrichtungsstil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schauplatz',
            old_name='architektur',
            new_name='beleuchtung',
        ),
        migrations.RenameField(
            model_name='schauplatz',
            old_name='bedeutung_oder_funktion',
            new_name='einrichtungsstil',
        ),
        migrations.RenameField(
            model_name='schauplatz',
            old_name='geheimnisse_und_legenden',
            new_name='geheimnisse_und_versteckte_elemente',
        ),
        migrations.RenameField(
            model_name='schauplatz',
            old_name='besitzer',
            new_name='nutzung',
        ),
        migrations.RenameField(
            model_name='schauplatz',
            old_name='typ',
            new_name='raumtyp',
        ),
        migrations.RenameField(
            model_name='schauplatz',
            old_name='geschichte_des_schauplatzes',
            new_name='spezielle_gegenstände',
        ),
        migrations.RemoveField(
            model_name='schauplatz',
            name='wichtige_personen',
        ),
        migrations.AddField(
            model_name='ortliste',
            name='architektur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='besitzer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='geheimnisse_und_legenden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='geschichte_des_schauplatzes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='typ',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='wichtige_personen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ortliste',
            name='zustand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
