# Generated by Django 5.1.1 on 2024-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_rename_architektur_schauplatz_beleuchtung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ortliste',
            name='architektur',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='besitzer',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='geheimnisse_und_legenden',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='geschichte_des_schauplatzes',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='wichtige_personen',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='zustand',
        ),
        migrations.AddField(
            model_name='ort',
            name='architektur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='bedeutung_oder_funktion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='besitzer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='gefahren_und_bedrohungen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='geheimnisse_und_legenden',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='geschichte_des_schauplatzes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='quests_und_interaktionsmöglichkeiten',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='typ',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='wichtige_personen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='zustand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
