# Generated by Django 5.1.1 on 2024-09-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_ortliste_architektur_remove_ortliste_besitzer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szene',
            name='chronologie',
            field=models.IntegerField(),
        ),
    ]
