# Generated by Django 5.1.1 on 2024-09-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_szene_chronologie'),
    ]

    operations = [
        migrations.AddField(
            model_name='figur',
            name='plot',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
