# Generated by Django 5.1.1 on 2024-09-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_figur_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='figur',
            name='ort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ort'),
        ),
    ]
