# Generated by Django 5.1.1 on 2024-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_figur_ort'),
    ]

    operations = [
        migrations.AddField(
            model_name='ort',
            name='beschreibung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
