# Generated by Django 5.1.1 on 2024-09-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_ort_beschreibung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ortliste',
            name='bedeutung_oder_funktion',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='flora_und_fauna',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='historie_und_hintergrund',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='klima_und_wetter',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='kulturelle_oder_religiöse_bedeutung',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='magische_oder_mystische_eigenschaften',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='politische_verhältnisse',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='ressourcen_und_reichtümer',
        ),
        migrations.RemoveField(
            model_name='ortliste',
            name='verbindungen_zu_anderen_orten',
        ),
    ]
