# Generated by Django 5.1.1 on 2024-09-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_remove_ortliste_bedeutung_oder_funktion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figur',
            name='krankheiten',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
