# Generated by Django 5.1.1 on 2024-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_figur_krankheiten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figur',
            name='krankheiten',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
