# Generated by Django 5.1.1 on 2024-09-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_figur_krankheiten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figur',
            name='krankheiten',
        ),
    ]
